OFS-146: changes with saving contract contribution plan details
openimis/openimis-be-contract_py pull request #23
Opened 2021-02-04 13:52 UTC by sniedzielski

This PR should be merged after https://github.com/openimis/openimis-be-contribution_plan_py/pull/22

In that PR I want to merge some fixes related to the changes on wiki page with approving contract (also valuation contract, submit, amend etc) and related them to the policies etc. This is necessary to work further on activatingPolicies when the payment is received (paid) etc.

2021-02-04 16:04 UTC, delcroip requested changes

2021-02-04 16:04 UTC, delcroip commented on contract/services.py
> +                    from core import datetime, datetimedelta
please create another function

2021-02-04 16:04 UTC, delcroip commented on contract/services.py
> +                    ccpd.date_valid_from = contract_details["contract_date_valid_from"]
add TODO: calculate the number of CCPD to create in order to cover the contract lenght

2021-02-04 16:04 UTC, delcroip commented on contract/services.py
> +                    if len(ccpd_results) == 1:
add TODO: support more that 2 CCPD

2021-02-05 15:52 UTC, sniedzielski commented
@delcroip I think that the most important issues are solved after changes related to the review

2021-02-08 09:00 UTC, delcroip approved these changes

2021-02-08 09:00 UTC, merged