OFS-146: activate policy on received proper payment and send email counter
openimis/openimis-be-contract_py pull request #24
Opened 2021-02-08 10:02 UTC by sniedzielski

2021-02-08 12:08 UTC, delcroip requested changes

2021-02-08 12:08 UTC, delcroip commented on contract/signals.py
> +        contract = ContractContributionPlanDetails.objects.filter(contribution_id=payment_detail[0].premium.id).first().contract_details.contract
A payment might concerns multiple contract, 
why not having related_name "contract_contribution_plan_details" for the contribution in the CCPD (https://github.com/openimis/openimis-be-contract_py/blob/05c1c5648ffbcca52a60450ca3b47db876249110/contract/models.py#L119) and having a query like
0- to check that this payment concerns a contract
PaymentDetail.filter(payment__id=int(instance.id)).select_related('premium__contract_contribution_plan_details__contract_details__contract).select_related('premium__contract_contribution_plan_details).filter(premium__contract_contribution_plan_details__isnull=false)

You could add the "only" statement to have only the fields you need (saves RAM)
 then if the payment include a contract payment:
1- check if the contract have payment attached to each contributions
(Nice to have)2- get all the payment related to all contribution that are part of the payment involving the contract (current and past)
3- check that  (nice to have: the sum of all) the payment match the value of all contributions
4-activate the insureepolicies of the contracts (can be severals)

if you don't do the nice to have please add todos

2021-02-08 13:27 UTC, sniedzielski commented on contract/signals.py
> +    payment_detail = list(PaymentDetail.objects.filter(payment__id=int(instance.id)))
0 point should be implemented here

2021-02-09 08:15 UTC, delcroip approved these changes

2021-02-09 08:15 UTC, merged